version: '3.8'

services:
    postgres:
        image: postgres:16-alpine
        container_name: insightboard-postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: insightboard
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 10s
            timeout: 5s
            retries: 5

    redis:
        image: redis:7-alpine
        container_name: insightboard-redis
        restart: unless-stopped
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 10s
            timeout: 5s
            retries: 5
        command: redis-server --appendonly yes

volumes:
    postgres_data:
        driver: local
    redis_data:
        driver: local

networks:
    default:
        name: insightboard-network
